FROM 'oven/bun' AS base
WORKDIR /home/bun/app


FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile


RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production --ignore-scripts

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

# copy production dependencies and source code into final image
FROM base AS release
COPY --from=install /temp/dev/node_modules node_modules
COPY --from=prerelease /home/bun/app/src src
COPY --from=prerelease /home/bun/app/package.json .

# run the app
USER bun
EXPOSE 8000/tcp
ENTRYPOINT [ "bun", "run", "dev" ]