export { default as StudentController } from './Student.controller'
export { default as ProfessorController } from './Professor.controller'
export { default as AdministrativeController } from './Administrative.controller'
export { default as ExternalController } from './External.controller'
export { default as GenericController } from './Generic.controller'
