export const ThesisPermissionsDict = {
  CREATE_THESIS: 'CREATE_THESIS',
  READ_THESIS: 'READ_THESIS',
  APROVE_THESIS_PHASE_1: 'APROVE_THESIS_PHASE_1',
  APROVE_THESIS_PHASE_2: 'APROVE_THESIS_PHASE_2',
  APROVE_THESIS_PHASE_3: 'APROVE_THESIS_PHASE_3',
  REQUEST_THESIS_JURY: 'REQUEST_THESIS_JURY',
  ASSIGN_THESIS_JURY: 'ASSIGN_THESIS_JURY',
  DOWNLOAD_THESIS_REPORT: 'DOWNLOAD_THESIS_REPORT',
} as const

export type ThesisPermissionsDict = keyof typeof ThesisPermissionsDict
