export const UnitPermissionsDict = {
  READ_UNIVERSITY: 'READ_UNIVERSITY',
  WRITE_UNIVERSITY: 'WRITE_UNIVERSITY',
  READ_FACULTY: 'READ_FACULTY',
  WRITE_FACULTY: 'WRITE_FACULTY',
  READ_DEPARTMENT: 'READ_DEPARTMENT',
  WRITE_DEPARTMENT: 'WRITE_DEPARTMENT',
  READ_SECTION: 'READ_SECTION',
  WRITE_SECTION: 'WRITE_SECTION',
  READ_AREAS: 'READ_AREAS',
  WRITE_AREAS: 'WRITE_AREAS',
  READ_SPECIALTIES: 'READ_SPECIALTIES',
  WRITE_SPECIALTIES: 'WRITE_SPECIALTIES',
} as const

export type UnitPermissionsDict =
  (typeof UnitPermissionsDict)[keyof typeof UnitPermissionsDict]
