name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      # Instala dependencias con Bun
      - name: Install dependencies
        run: bun install

      # Construye el proyecto
      - name: Build project
        run: bun run build && cp ./dist/index.html ./dist/404.html

      # Crea archivo CNAME si es necesario para el dominio personalizado
      #- name: Create CNAME file
      #  run: echo 'dominio' > ./dist/CNAME

      # Sube los archivos de construcción listos para producción
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Configura Google Cloud SDK para subir a Google Cloud Storage
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      # Sube el contenido del directorio ./dist a tu bucket de GCS
      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r ./dist gs://lyceum-frontend
