/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SeguridadImport } from './routes/seguridad'
import { Route as PreguntasFrecuentesImport } from './routes/preguntas-frecuentes'
import { Route as CursosImport } from './routes/cursos'
import { Route as IndexImport } from './routes/index'
import { Route as SeguridadIndexImport } from './routes/seguridad/index'
import { Route as PreguntasFrecuentesIndexImport } from './routes/preguntas-frecuentes/index'
import { Route as CursosIndexImport } from './routes/cursos/index'
import { Route as UnidadNameImport } from './routes/unidad/$name'
import { Route as SeguridadRolesImport } from './routes/seguridad/roles'
import { Route as SeguridadPermisosImport } from './routes/seguridad/permisos'
import { Route as CursosRetiroAlumnosImport } from './routes/cursos/retiroAlumnos'
import { Route as UnidadNameIndexImport } from './routes/unidad/$name/index'
import { Route as CursosAlumnosRiesgoIndexImport } from './routes/cursos/alumnosRiesgo/index'
import { Route as UnidadNameUsuariosImport } from './routes/unidad/$name/usuarios'
import { Route as UnidadNameSubunidadesImport } from './routes/unidad/$name/subunidades'
import { Route as UnidadNameRolesImport } from './routes/unidad/$name/roles'
import { Route as CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexImport } from './routes/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/index'

// Create/Update Routes

const SeguridadRoute = SeguridadImport.update({
  path: '/seguridad',
  getParentRoute: () => rootRoute,
} as any)

const PreguntasFrecuentesRoute = PreguntasFrecuentesImport.update({
  path: '/preguntas-frecuentes',
  getParentRoute: () => rootRoute,
} as any)

const CursosRoute = CursosImport.update({
  path: '/cursos',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SeguridadIndexRoute = SeguridadIndexImport.update({
  path: '/',
  getParentRoute: () => SeguridadRoute,
} as any)

const PreguntasFrecuentesIndexRoute = PreguntasFrecuentesIndexImport.update({
  path: '/',
  getParentRoute: () => PreguntasFrecuentesRoute,
} as any)

const CursosIndexRoute = CursosIndexImport.update({
  path: '/',
  getParentRoute: () => CursosRoute,
} as any)

const UnidadNameRoute = UnidadNameImport.update({
  path: '/unidad/$name',
  getParentRoute: () => rootRoute,
} as any)

const SeguridadRolesRoute = SeguridadRolesImport.update({
  path: '/roles',
  getParentRoute: () => SeguridadRoute,
} as any)

const SeguridadPermisosRoute = SeguridadPermisosImport.update({
  path: '/permisos',
  getParentRoute: () => SeguridadRoute,
} as any)

const CursosRetiroAlumnosRoute = CursosRetiroAlumnosImport.update({
  path: '/retiroAlumnos',
  getParentRoute: () => CursosRoute,
} as any)

const UnidadNameIndexRoute = UnidadNameIndexImport.update({
  path: '/',
  getParentRoute: () => UnidadNameRoute,
} as any)

const CursosAlumnosRiesgoIndexRoute = CursosAlumnosRiesgoIndexImport.update({
  path: '/alumnosRiesgo/',
  getParentRoute: () => CursosRoute,
} as any)

const UnidadNameUsuariosRoute = UnidadNameUsuariosImport.update({
  path: '/usuarios',
  getParentRoute: () => UnidadNameRoute,
} as any)

const UnidadNameSubunidadesRoute = UnidadNameSubunidadesImport.update({
  path: '/subunidades',
  getParentRoute: () => UnidadNameRoute,
} as any)

const UnidadNameRolesRoute = UnidadNameRolesImport.update({
  path: '/roles',
  getParentRoute: () => UnidadNameRoute,
} as any)

const CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute =
  CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexImport.update({
    path: '/alumnosRiesgo/$codigoAlumnoRiesgo/',
    getParentRoute: () => CursosRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/cursos': {
      id: '/cursos'
      path: '/cursos'
      fullPath: '/cursos'
      preLoaderRoute: typeof CursosImport
      parentRoute: typeof rootRoute
    }
    '/preguntas-frecuentes': {
      id: '/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/preguntas-frecuentes'
      preLoaderRoute: typeof PreguntasFrecuentesImport
      parentRoute: typeof rootRoute
    }
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadImport
      parentRoute: typeof rootRoute
    }
    '/cursos/retiroAlumnos': {
      id: '/cursos/retiroAlumnos'
      path: '/retiroAlumnos'
      fullPath: '/cursos/retiroAlumnos'
      preLoaderRoute: typeof CursosRetiroAlumnosImport
      parentRoute: typeof CursosImport
    }
    '/seguridad/permisos': {
      id: '/seguridad/permisos'
      path: '/permisos'
      fullPath: '/seguridad/permisos'
      preLoaderRoute: typeof SeguridadPermisosImport
      parentRoute: typeof SeguridadImport
    }
    '/seguridad/roles': {
      id: '/seguridad/roles'
      path: '/roles'
      fullPath: '/seguridad/roles'
      preLoaderRoute: typeof SeguridadRolesImport
      parentRoute: typeof SeguridadImport
    }
    '/unidad/$name': {
      id: '/unidad/$name'
      path: '/unidad/$name'
      fullPath: '/unidad/$name'
      preLoaderRoute: typeof UnidadNameImport
      parentRoute: typeof rootRoute
    }
    '/cursos/': {
      id: '/cursos/'
      path: '/'
      fullPath: '/cursos/'
      preLoaderRoute: typeof CursosIndexImport
      parentRoute: typeof CursosImport
    }
    '/preguntas-frecuentes/': {
      id: '/preguntas-frecuentes/'
      path: '/'
      fullPath: '/preguntas-frecuentes/'
      preLoaderRoute: typeof PreguntasFrecuentesIndexImport
      parentRoute: typeof PreguntasFrecuentesImport
    }
    '/seguridad/': {
      id: '/seguridad/'
      path: '/'
      fullPath: '/seguridad/'
      preLoaderRoute: typeof SeguridadIndexImport
      parentRoute: typeof SeguridadImport
    }
    '/unidad/$name/roles': {
      id: '/unidad/$name/roles'
      path: '/roles'
      fullPath: '/unidad/$name/roles'
      preLoaderRoute: typeof UnidadNameRolesImport
      parentRoute: typeof UnidadNameImport
    }
    '/unidad/$name/subunidades': {
      id: '/unidad/$name/subunidades'
      path: '/subunidades'
      fullPath: '/unidad/$name/subunidades'
      preLoaderRoute: typeof UnidadNameSubunidadesImport
      parentRoute: typeof UnidadNameImport
    }
    '/unidad/$name/usuarios': {
      id: '/unidad/$name/usuarios'
      path: '/usuarios'
      fullPath: '/unidad/$name/usuarios'
      preLoaderRoute: typeof UnidadNameUsuariosImport
      parentRoute: typeof UnidadNameImport
    }
    '/cursos/alumnosRiesgo/': {
      id: '/cursos/alumnosRiesgo/'
      path: '/alumnosRiesgo'
      fullPath: '/cursos/alumnosRiesgo'
      preLoaderRoute: typeof CursosAlumnosRiesgoIndexImport
      parentRoute: typeof CursosImport
    }
    '/unidad/$name/': {
      id: '/unidad/$name/'
      path: '/'
      fullPath: '/unidad/$name/'
      preLoaderRoute: typeof UnidadNameIndexImport
      parentRoute: typeof UnidadNameImport
    }
    '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/': {
      id: '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/'
      path: '/alumnosRiesgo/$codigoAlumnoRiesgo'
      fullPath: '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo'
      preLoaderRoute: typeof CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexImport
      parentRoute: typeof CursosImport
    }
  }
}

// Create and export the route tree

interface CursosRouteChildren {
  CursosRetiroAlumnosRoute: typeof CursosRetiroAlumnosRoute
  CursosIndexRoute: typeof CursosIndexRoute
  CursosAlumnosRiesgoIndexRoute: typeof CursosAlumnosRiesgoIndexRoute
  CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute: typeof CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute
}

const CursosRouteChildren: CursosRouteChildren = {
  CursosRetiroAlumnosRoute: CursosRetiroAlumnosRoute,
  CursosIndexRoute: CursosIndexRoute,
  CursosAlumnosRiesgoIndexRoute: CursosAlumnosRiesgoIndexRoute,
  CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute:
    CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute,
}

const CursosRouteWithChildren =
  CursosRoute._addFileChildren(CursosRouteChildren)

interface PreguntasFrecuentesRouteChildren {
  PreguntasFrecuentesIndexRoute: typeof PreguntasFrecuentesIndexRoute
}

const PreguntasFrecuentesRouteChildren: PreguntasFrecuentesRouteChildren = {
  PreguntasFrecuentesIndexRoute: PreguntasFrecuentesIndexRoute,
}

const PreguntasFrecuentesRouteWithChildren =
  PreguntasFrecuentesRoute._addFileChildren(PreguntasFrecuentesRouteChildren)

interface SeguridadRouteChildren {
  SeguridadPermisosRoute: typeof SeguridadPermisosRoute
  SeguridadRolesRoute: typeof SeguridadRolesRoute
  SeguridadIndexRoute: typeof SeguridadIndexRoute
}

const SeguridadRouteChildren: SeguridadRouteChildren = {
  SeguridadPermisosRoute: SeguridadPermisosRoute,
  SeguridadRolesRoute: SeguridadRolesRoute,
  SeguridadIndexRoute: SeguridadIndexRoute,
}

const SeguridadRouteWithChildren = SeguridadRoute._addFileChildren(
  SeguridadRouteChildren,
)

interface UnidadNameRouteChildren {
  UnidadNameRolesRoute: typeof UnidadNameRolesRoute
  UnidadNameSubunidadesRoute: typeof UnidadNameSubunidadesRoute
  UnidadNameUsuariosRoute: typeof UnidadNameUsuariosRoute
  UnidadNameIndexRoute: typeof UnidadNameIndexRoute
}

const UnidadNameRouteChildren: UnidadNameRouteChildren = {
  UnidadNameRolesRoute: UnidadNameRolesRoute,
  UnidadNameSubunidadesRoute: UnidadNameSubunidadesRoute,
  UnidadNameUsuariosRoute: UnidadNameUsuariosRoute,
  UnidadNameIndexRoute: UnidadNameIndexRoute,
}

const UnidadNameRouteWithChildren = UnidadNameRoute._addFileChildren(
  UnidadNameRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRouteWithChildren
  '/seguridad': typeof SeguridadRouteWithChildren
  '/cursos/retiroAlumnos': typeof CursosRetiroAlumnosRoute
  '/seguridad/permisos': typeof SeguridadPermisosRoute
  '/seguridad/roles': typeof SeguridadRolesRoute
  '/unidad/$name': typeof UnidadNameRouteWithChildren
  '/cursos/': typeof CursosIndexRoute
  '/preguntas-frecuentes/': typeof PreguntasFrecuentesIndexRoute
  '/seguridad/': typeof SeguridadIndexRoute
  '/unidad/$name/roles': typeof UnidadNameRolesRoute
  '/unidad/$name/subunidades': typeof UnidadNameSubunidadesRoute
  '/unidad/$name/usuarios': typeof UnidadNameUsuariosRoute
  '/cursos/alumnosRiesgo': typeof CursosAlumnosRiesgoIndexRoute
  '/unidad/$name/': typeof UnidadNameIndexRoute
  '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo': typeof CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cursos/retiroAlumnos': typeof CursosRetiroAlumnosRoute
  '/seguridad/permisos': typeof SeguridadPermisosRoute
  '/seguridad/roles': typeof SeguridadRolesRoute
  '/cursos': typeof CursosIndexRoute
  '/preguntas-frecuentes': typeof PreguntasFrecuentesIndexRoute
  '/seguridad': typeof SeguridadIndexRoute
  '/unidad/$name/roles': typeof UnidadNameRolesRoute
  '/unidad/$name/subunidades': typeof UnidadNameSubunidadesRoute
  '/unidad/$name/usuarios': typeof UnidadNameUsuariosRoute
  '/cursos/alumnosRiesgo': typeof CursosAlumnosRiesgoIndexRoute
  '/unidad/$name': typeof UnidadNameIndexRoute
  '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo': typeof CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/cursos': typeof CursosRouteWithChildren
  '/preguntas-frecuentes': typeof PreguntasFrecuentesRouteWithChildren
  '/seguridad': typeof SeguridadRouteWithChildren
  '/cursos/retiroAlumnos': typeof CursosRetiroAlumnosRoute
  '/seguridad/permisos': typeof SeguridadPermisosRoute
  '/seguridad/roles': typeof SeguridadRolesRoute
  '/unidad/$name': typeof UnidadNameRouteWithChildren
  '/cursos/': typeof CursosIndexRoute
  '/preguntas-frecuentes/': typeof PreguntasFrecuentesIndexRoute
  '/seguridad/': typeof SeguridadIndexRoute
  '/unidad/$name/roles': typeof UnidadNameRolesRoute
  '/unidad/$name/subunidades': typeof UnidadNameSubunidadesRoute
  '/unidad/$name/usuarios': typeof UnidadNameUsuariosRoute
  '/cursos/alumnosRiesgo/': typeof CursosAlumnosRiesgoIndexRoute
  '/unidad/$name/': typeof UnidadNameIndexRoute
  '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/': typeof CursosAlumnosRiesgoCodigoAlumnoRiesgoIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cursos'
    | '/preguntas-frecuentes'
    | '/seguridad'
    | '/cursos/retiroAlumnos'
    | '/seguridad/permisos'
    | '/seguridad/roles'
    | '/unidad/$name'
    | '/cursos/'
    | '/preguntas-frecuentes/'
    | '/seguridad/'
    | '/unidad/$name/roles'
    | '/unidad/$name/subunidades'
    | '/unidad/$name/usuarios'
    | '/cursos/alumnosRiesgo'
    | '/unidad/$name/'
    | '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cursos/retiroAlumnos'
    | '/seguridad/permisos'
    | '/seguridad/roles'
    | '/cursos'
    | '/preguntas-frecuentes'
    | '/seguridad'
    | '/unidad/$name/roles'
    | '/unidad/$name/subunidades'
    | '/unidad/$name/usuarios'
    | '/cursos/alumnosRiesgo'
    | '/unidad/$name'
    | '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo'
  id:
    | '__root__'
    | '/'
    | '/cursos'
    | '/preguntas-frecuentes'
    | '/seguridad'
    | '/cursos/retiroAlumnos'
    | '/seguridad/permisos'
    | '/seguridad/roles'
    | '/unidad/$name'
    | '/cursos/'
    | '/preguntas-frecuentes/'
    | '/seguridad/'
    | '/unidad/$name/roles'
    | '/unidad/$name/subunidades'
    | '/unidad/$name/usuarios'
    | '/cursos/alumnosRiesgo/'
    | '/unidad/$name/'
    | '/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CursosRoute: typeof CursosRouteWithChildren
  PreguntasFrecuentesRoute: typeof PreguntasFrecuentesRouteWithChildren
  SeguridadRoute: typeof SeguridadRouteWithChildren
  UnidadNameRoute: typeof UnidadNameRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CursosRoute: CursosRouteWithChildren,
  PreguntasFrecuentesRoute: PreguntasFrecuentesRouteWithChildren,
  SeguridadRoute: SeguridadRouteWithChildren,
  UnidadNameRoute: UnidadNameRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cursos",
        "/preguntas-frecuentes",
        "/seguridad",
        "/unidad/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/cursos": {
      "filePath": "cursos.tsx",
      "children": [
        "/cursos/retiroAlumnos",
        "/cursos/",
        "/cursos/alumnosRiesgo/",
        "/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/"
      ]
    },
    "/preguntas-frecuentes": {
      "filePath": "preguntas-frecuentes.tsx",
      "children": [
        "/preguntas-frecuentes/"
      ]
    },
    "/seguridad": {
      "filePath": "seguridad.tsx",
      "children": [
        "/seguridad/permisos",
        "/seguridad/roles",
        "/seguridad/"
      ]
    },
    "/cursos/retiroAlumnos": {
      "filePath": "cursos/retiroAlumnos.tsx",
      "parent": "/cursos"
    },
    "/seguridad/permisos": {
      "filePath": "seguridad/permisos.tsx",
      "parent": "/seguridad"
    },
    "/seguridad/roles": {
      "filePath": "seguridad/roles.tsx",
      "parent": "/seguridad"
    },
    "/unidad/$name": {
      "filePath": "unidad/$name.tsx",
      "children": [
        "/unidad/$name/roles",
        "/unidad/$name/subunidades",
        "/unidad/$name/usuarios",
        "/unidad/$name/"
      ]
    },
    "/cursos/": {
      "filePath": "cursos/index.tsx",
      "parent": "/cursos"
    },
    "/preguntas-frecuentes/": {
      "filePath": "preguntas-frecuentes/index.tsx",
      "parent": "/preguntas-frecuentes"
    },
    "/seguridad/": {
      "filePath": "seguridad/index.tsx",
      "parent": "/seguridad"
    },
    "/unidad/$name/roles": {
      "filePath": "unidad/$name/roles.tsx",
      "parent": "/unidad/$name"
    },
    "/unidad/$name/subunidades": {
      "filePath": "unidad/$name/subunidades.tsx",
      "parent": "/unidad/$name"
    },
    "/unidad/$name/usuarios": {
      "filePath": "unidad/$name/usuarios.tsx",
      "parent": "/unidad/$name"
    },
    "/cursos/alumnosRiesgo/": {
      "filePath": "cursos/alumnosRiesgo/index.tsx",
      "parent": "/cursos"
    },
    "/unidad/$name/": {
      "filePath": "unidad/$name/index.tsx",
      "parent": "/unidad/$name"
    },
    "/cursos/alumnosRiesgo/$codigoAlumnoRiesgo/": {
      "filePath": "cursos/alumnosRiesgo/$codigoAlumnoRiesgo/index.tsx",
      "parent": "/cursos"
    }
  }
}
ROUTE_MANIFEST_END */
