name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Instala Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          export BUN_INSTALL="$HOME/.bun"
          export PATH="$BUN_INSTALL/bin:$PATH"

      # Instala dependencias con Bun
      - name: Install dependencies
        run: bun install

      # Construye el proyecto
      - name: Build project
        run: bun run build

      # Crea archivo CNAME si es necesario para el dominio personalizado
      #- name: Create CNAME file
      #  run: echo 'dominio' > ./dist/CNAME

      # Sube los archivos de construcción listos para producción
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist

      # Configura Google Cloud SDK para subir a Google Cloud Storage
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          project_id: lyceum-439813

      # Sube el contenido del directorio ./dist a tu bucket de GCS
      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r ./dist gs://lyceum-frontend
